[tool.isort]
profile = "black"
src_paths = ["python/mlc_chat"]
known_third_party = ["numpy", "tvm", "tqdm", "torch", "transformers"]

[tool.black]
line-length = 100

[tool.mypy]
ignore_missing_imports = true
show_column_numbers = true
show_error_context = true
follow_imports = "skip"
ignore_errors = false
strict_optional = false

[tool.pylint.messages_control]
max-line-length = 100
disable = """
duplicate-code,
"""